### PR TITLE
Various small changes to support fully automated network domain setup in our organization

### PR DESCRIPTION
**Pull request by ErikEngerd**
We have been using this java client for our fully automated setup of network domains. This required a few small changes that we would like to have included in the java client.

### CODE REVIEW

**Comment by tintoy** [comment]
Thanks for the contribution! We'll sort this out first thing on Monday :)

**Comment by tintoy** [comment]
Sorry, I only just got around to this - thanks again.

**Comment by ErikEngerd** [comment]
Hi Adam

Thanks for incorporating our changes.
By the way, is support for the 2.4 APIs already planned? We would need this for the support of anti-affinity rules in the 2.4 API.

Cheers 
  Erik

On December 22, 2016 7:52:07 PM GMT+01:00, Adam Friedman <notifications@github.com> wrote:
>Sorry, I only just got around to this - thanks again.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/DimensionDataCBUSydney/dimensiondata-cloud-java-client/pull/11#issuecomment-268865258

--
Erik

**Comment by tintoy** [comment]
Hi Erik,

I'm not sure who maintains this client at the moment; let me reach out to a couple of people and get back to you.

**Pull request merged**
